version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    depends_on:
#      - unit_tests
      - bank_simulator

  bank_simulator:
    container_name: bank_simulator
    image: bbyars/mountebank:2.8.1
    ports:
      - "2525:2525"
      - "8080:8080"
    command: --configfile /imposters/bank_simulator.ejs
    volumes:
      - type: bind
        source: ./imposters
        target: /imposters

  aspire_dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    container_name: aspire_dashboard
    ports:
      - "18888:18888"
      - "4317:18889"
    restart: always
    
#  unit_tests:
#    image: mcr.microsoft.com/dotnet/sdk:8.0
#    container_name: unit_tests
#    working_dir: /src
#    volumes:
#      - .:/src
#    command: [ "dotnet", "test" ]
#
#  smoke_tests:
#    image: bash:latest
#    container_name: smoke_tests
#    working_dir: /src
#    volumes:
#      - .:/src
#    command: [ "./test/PaymentGateway.Api.Tests/smoke/smoke_test.sh" ]
#    depends_on:
#      - app
#
#  contract_tests:
#    image: node:16
#    container_name: contract_tests
#    working_dir: /src
#    volumes:
#      - .:/src
#    command: [ "node", "test/PaymentGateway.Api.Tests/contract/contract_test.js" ]
#    depends_on:
#      - app
