# fly.toml app configuration file generated for payment-gateway-challenge-dotnet-dark-surf-9016 on 2024-12-07T12:48:20+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'payment-gateway-challenge-dotnet'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
