name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test with coverage
        run: |
          dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"
      - name: Publish Code Coverage Report
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Assert Coverage
        run: |
          COVERAGE=$(curl -s https://codecov.io/api/gh/umr55766/payment-gateway-challenge-dotnet/commits/main | jq '.total.coverage')
          if (( $(echo "$COVERAGE < 100" | bc -l) )); then
            echo "Code coverage is below the 50% threshold. Current coverage is $COVERAGE%"
            exit 1
          else
            echo "Code coverage is sufficient: $COVERAGE%"
          fi
